<h1>Update the user</h1>
<hr>
<form action="/users/<?= htmlspecialchars($id)?>" method="post">
    <input type="hidden" name="_METHOD" value="PATCH">
    <div>
        <label>
            Nickname:
            <input type="text" name="user[nickname]" value="<?= htmlspecialchars($user['nickname']) ?>">
        </label>
        <?php if (isset($errors['nickname'])): ?>
            <div><?= $errors['nickname'] ?></div>
        <?php endif ?>
    </div>
    <div>
        <label>
            Email:
            <input type="email" name="user[email]" value="<?= htmlspecialchars($user['email']) ?>">
        </label>
        <?php if (isset($errors['email'])): ?>
            <div><?= $errors['email'] ?></div>
        <?php endif ?>
    </div>
    <input type="submit" name="Submit">
</form>

<form action="/users/<?= $id?>" method="post">
<?php var_dump($id);?>
    <input type="hidden" name="_METHOD" value="DELETE">
    <input type="submit" value="Remove">
</form>