<h1>Users</h1>


<?php if (count($flash) > 0) : ?>
    <?php foreach ($flash as $messages) : ?>
        <?php foreach ($messages as $message) : ?>
            <h3><?= $message ?></h3>
        <?php endforeach ?>
    <?php endforeach ?>
<?php endif ?>
<hr>


<form action = >
    <input type = "search" name="term">
    <input type = "submit" value = "Search">
</form>
<hr>
Nicknames: 
<ul>
    <?php foreach($users as $user): ?>
        <li><?php echo(htmlspecialchars($user['nickname']))?></li>
    <?php endforeach ?>
</ul>