<h1>Users</h1>
<?php if (count($flash) > 0) : ?>
    <?php foreach ($flash as $messages) : ?>
        <?php foreach ($messages as $message) : ?>
            <h3><?= $message ?></h3>
        <?php endforeach ?>
    <?php endforeach ?>
<?php endif ?>
<form action="/session" method="post">
    <input type="hidden" name="_METHOD" value="DELETE">
    <input type="submit" value="Sign Out">
</form>
<form action = '/users/new' method = 'get'>
        <input type = "submit" value = "Create User">
</form>
<hr>
<form action = '/users' method = 'get'>
    <input type = "search" name="term">
    <input type = "submit" value = "Search">
</form>
<hr>
Nicknames: 
<ul>
    <?php foreach($users as $user): ?>
        <li><a href="/users/<?= htmlspecialchars($user['id'])?>"><?= htmlspecialchars($user['nickname'])?></a>
        <a href="/users/<?= htmlspecialchars($user['id'])?>/edit"><input type="submit" value="Edit"></li>
    <?php endforeach ?>
</ul>