<h1>Users</h1>
<form action = '/users/new' method = 'get'>
        <input type = "submit" value = "Create User">
</form>
<?php if (count($flash) > 0) : ?>
    <?php foreach ($flash as $messages) : ?>
        <?php foreach ($messages as $message) : ?>
            <h3><?= $message ?></h3>
        <?php endforeach ?>
    <?php endforeach ?>
<?php endif ?>
<hr>
<form action = '/users' method = 'get'>
    <input type = "search" name="term">
    <input type = "submit" value = "Search">
</form>
<hr>
Nicknames: 
<ul>
    <?php foreach($users as $user): ?>
        <li><?php echo(htmlspecialchars($user['nickname']))?></li>
    <?php endforeach ?>
</ul>